push!(LOAD_PATH, joinpath(@__DIR__, "src"))

using CubeTools
using StaticArrays

title       = ("H2 molecule", "Generated by CubeTools.jl")
origin      = SVector{3, Float64}(0.0, 0.0, 0.0)

npoints     = SVector{3, Int}(100, 100, 100)
axes        = SMatrix{3, 3, Float64, 9}(10.0, 0.0, 0.0,
                                        0.0, 10.0, 0.0,
                                        0.0, 0.0, 10.0)

dl = axes./npoints

periodicity = SVector{3, Bool}(false, false, false)

atoms       = [Atom(1, 1.0, SVector{3, Float64}(5.0, 5.0, 3.0)),
               Atom(1, 1.0, SVector{3, Float64}(5.0, 5.0, 7.0))]

# generate s1 orbital as superposition of H atom contributions
data = Float64[]
for i in 1:npoints[1]
    for j in 1:npoints[2]
        for k in 1:npoints[3]
            x = origin[1] + (i - 1) * dl[1, 1] + (j - 1) * dl[2, 1] + (k - 1) * dl[3, 1]
            y = origin[2] + (i - 1) * dl[1, 2] + (j - 1) * dl[2, 2] + (k - 1) * dl[3, 2]
            z = origin[3] + (i - 1) * dl[1, 3] + (j - 1) * dl[2, 3] + (k - 1) * dl[3, 3]
            val = sum(exp(-sqrt((x - atom.position[1])^2 + (y - atom.position[2])^2 + (z - atom.position[3])^2)) for atom in atoms)
            push!(data, val)
        end
    end
end

H2 = CubeFile(title, origin, dl, npoints, periodicity, atoms, data)

write_cube(H2, "H2.cube")
