# Sobrecarga dos operadores aritméticos para CubeFile.
# Todos os operadores binários exigem que os dois arquivos sejam compatíveis:
# mesma origem, mesmos vetores de malha e mesmo número de pontos.
import Base: +, -, *, /


# Verifica se dois CubeFiles têm malhas compatíveis para operações elemento a elemento.
function _verificar_compatibilidade(A::CubeFile, B::CubeFile)
    A.origin  != B.origin  && error("A origem dos dois arquivos cube não é a mesma.")
    A.dl      != B.dl      && error("Os vetores de malha dos dois arquivos cube não são os mesmos.")
    A.npoints != B.npoints && error("O número de pontos dos dois arquivos cube não é o mesmo.")
end


function +(A::CubeFile, B::CubeFile)
    _verificar_compatibilidade(A, B)
    CubeFile("Sum of Two Cube Files", "Generated by CubeTools.jl",
             A.origin, A.dl, A.npoints, A.periodicity, A.atoms, A.data .+ B.data)
end

function -(A::CubeFile, B::CubeFile)
    _verificar_compatibilidade(A, B)
    CubeFile("Difference of Two Cube Files", "Generated by CubeTools.jl",
             A.origin, A.dl, A.npoints, A.periodicity, A.atoms, A.data .- B.data)
end

# Multiplicação por escalar (escalar × CubeFile e CubeFile × escalar)
function *(A::CubeFile, scalar::Real)
    CubeFile("Scaled Cube File", "Generated by CubeTools.jl",
             A.origin, A.dl, A.npoints, A.periodicity, A.atoms, A.data .* scalar)
end

*(scalar::Real, A::CubeFile) = A * scalar

function /(A::CubeFile, scalar::Real)
    CubeFile("Scaled Cube File", "Generated by CubeTools.jl",
             A.origin, A.dl, A.npoints, A.periodicity, A.atoms, A.data ./ scalar)
end