import Base: +, -, *, /

function +(A::CubeFile, B::CubeFile)
    
    # Teste de Compatibilidade dos Arquivos
    if A.origin != B.origin
        error("A Origem dos dois arquivos cube não é a mesma.")
    end
    
    if A.dl != B.dl
        error("Os eixos dos dois arquivos cube não são os mesmos.")
    end
    
    if A.npoints != B.npoints
        error("O número de pontos dos dois arquivos cube não é o mesmo.")
    end

    # Usa arquivo A como base para o resultado
    title = ("Sum of Two Cube Files", "Generated by CubeTools.jl")
    origin      = A.origin
    dl          = A.dl
    npoints     = A.npoints
    periodicity = A.periodicity
    atoms       = A.atoms
    data        = A.data .+ B.data

    # Cria o novo arquivo cube com os dados somados
    return CubeFile(title, origin, dl, npoints, periodicity, atoms, data)
end

function -(A::CubeFile, B::CubeFile)
    
    # Teste de Compatibilidade dos Arquivos
    if A.origin != B.origin
        error("A Origem dos dois arquivos cube não é a mesma.")
    end
    
    if A.dl != B.dl
        error("Os eixos dos dois arquivos cube não são os mesmos.")
    end
    
    if A.npoints != B.npoints
        error("O número de pontos dos dois arquivos cube não é o mesmo.")
    end

    # Usa arquivo A como base para o resultado
    title = ("Difference of Two Cube Files", "Generated by CubeTools.jl")
    origin      = A.origin
    dl          = A.dl
    npoints     = A.npoints
    periodicity = A.periodicity
    atoms       = A.atoms
    data        = A.data .- B.data

    # Cria o novo arquivo cube com os dados somados
    return CubeFile(title, origin, dl, npoints, periodicity, atoms, data)
end 

function *(A::CubeFile, scalar::Real)
    title = ("Scaled Cube File", "Generated by CubeTools.jl")
    origin      = A.origin
    dl          = A.dl
    npoints     = A.npoints
    periodicity = A.periodicity
    atoms       = A.atoms
    data        = A.data .* scalar

    return CubeFile(title, origin, dl, npoints, periodicity, atoms, data)
end

*(scalar::Real, A::CubeFile) = A * scalar


function /(A::CubeFile, scalar::Real)
    title = ("Scaled Cube File", "Generated by CubeTools.jl")
    origin      = A.origin
    dl          = A.dl
    npoints     = A.npoints
    periodicity = A.periodicity
    atoms       = A.atoms
    data        = A.data ./ scalar

    return CubeFile(title, origin, dl, npoints, periodicity, atoms, data)
end